repositories:
  # aws-infrastructure helm repository
  #
  # When developing charts that will later be merged, it can be helpful to instead point at a branch:
  # url: 'https://raw.githubusercontent.com/<account>/aws-infrastructure/<branch>/helm_repo/'
  - name: 'aws-infrastructure'
    url: 'https://raw.githubusercontent.com/fogies/aws-infrastructure/main/helm_repo/'

  - name: 'couchdb'
    url: 'https://apache.github.io/couchdb-helm'

releases:
  # ingress-crd contains CRDs required by cert-manager and by ingress
  - name: 'ingress-crd'
    namespace: 'ingress-crd'
    chart: 'aws-infrastructure/ingress-crd'
    version: '0.5.0'

  # cert-manager
  - name: 'cert-manager'
    namespace: 'cert-manager'
    chart: 'aws-infrastructure/cert-manager'
    version: '1.6.1'
    needs:
      - 'ingress-crd'

  # ingress
  - name: 'ingress'
    namespace: 'ingress'
    chart: 'aws-infrastructure/ingress'
    version: '0.7.0'
    needs:
      - 'ingress-crd'
    # values:
    #   - # To enable DEBUG logging for Traefik
    #     traefik:
    #       logs:
    #         general:
    #           level: 'DEBUG'

  # CouchDB instance for development
  - name: 'migraine-database-dev'
    namespace: 'migraine-database-dev'
    chart: 'couchdb/couchdb'
    version: '3.3.4'
    values:
      - './values/secrets_couchdb_dev_generated.values.yaml'
        # adminUsername: 'XXXXXXXXXX'
        # adminPassword: 'XXXXXXXXXX'
        # cookieAuthSecret: 'XXXXXXXXXX'
        # couchdbConfig:
        #   couchdb:
        #     uuid: 'XXXXXXXXXX'
      - clusterSize: 3
        image:
          repository: 'couchdb'
          tag: '3.2.0'
          pullPolicy: 'Always'
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

  # CouchDB instance for production
  - name: 'migraine-database-prod'
    namespace: 'migraine-database-prod'
    chart: 'couchdb/couchdb'
    version: '3.3.4'
    values:
      - './values/secrets_couchdb_prod_generated.values.yaml'
        # adminUsername: 'XXXXXXXXXX'
        # adminPassword: 'XXXXXXXXXX'
        # cookieAuthSecret: 'XXXXXXXXXX'
        # couchdbConfig:
        #   couchdb:
        #     uuid: 'XXXXXXXXXX'
      - clusterSize: 3
        image:
          repository: 'couchdb'
          tag: '3.2.0'
          pullPolicy: 'Always'
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi

  # migraine
  # Installed from a local chart, managed in helmfile-config.yaml
  - name: 'migraine'
    namespace: 'migraine'
    chart: './charts/migraine.tgz'
    needs:
      - 'ingress'
    values:
      - './values/ecr_generated.values.yaml'
        # registryUrl: 'XXXXXXXXXX'
        # registryUser: 'XXXXXXXXXX'
        # registryPassword: 'XXXXXXXXXX'
      - './values/secrets_flask_prod_generated.values.yaml'
        # flask:
        #   baseurl: 'XXXXXXXXXX'
        #   secret_key: 'XXXXXXXXXX'
        #   database_url: 'XXXXXXXXXX'
        #   database_admin:
        #     user: 'XXXXXXXXXX'
        #     password: 'XXXXXXXXXX'
      - tls:
          # Should be 'letsencrypt-staging' or 'letsencrypt'
          issuer: 'letsencrypt'

helmDefaults:
  # Prefer explicit management of CRDs via releases
  args:
    - '--skip-crds'

# Prefer explicit errors
missingFileHandler: 'Error'

