#
# Database receives all traffic at /db/.
#

---

#
# Middleware to strip /db/ prefix before passing to database.
#

apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'Middleware'

metadata:
  name: '{{ .Release.Name }}-ingress-couchdb-stripprefix-db'

spec:
  stripPrefix:
    prefixes:
      - '/db'
    forceSlash: false

---

#
# Production route.
#

apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'IngressRoute'

metadata:
  name: '{{ .Release.Name }}-ingress-couchdb-prod'

spec:
  entryPoints:
    - 'websecure'
  routes:
    - kind: 'Rule'
      match: 'HostRegexp(`migraineapp.org`) && PathPrefix(`/db/`)'
      priority: 10000
      middlewares:
        - name: 'migraine-cors'
        - name: '{{ .Release.Name }}-ingress-couchdb-stripprefix-db'
      services:
        - kind: 'Service'
          name: 'couchdb-proxy-cookie-prod'
          port: 80
          # Proxied to here:
          # name: 'migraine-database-prod-svc-couchdb'
          # namespace: 'migraine-database-prod'
          # port: 5984
  tls:
    secretName: {{ .Values.tls.tlsSecret | squote }}

---

#
# Development route.
#

apiVersion: 'traefik.containo.us/v1alpha1'
kind: 'IngressRoute'

metadata:
  name: '{{ .Release.Name }}-ingress-couchdb-dev'

spec:
  entryPoints:
    - 'websecure'
  routes:
    - kind: 'Rule'
      match: 'HostRegexp(`dev.migraineapp.org`) && PathPrefix(`/db/`)'
      priority: 10000
      middlewares:
        - name: 'migraine-cors'
        - name: '{{ .Release.Name }}-ingress-couchdb-stripprefix-db'
      services:
        - kind: 'Service'
          name: 'couchdb-proxy-cookie-dev'
          port: 80
          # Proxied to here:
          # name: 'migraine-database-dev-svc-couchdb'
          # namespace: 'migraine-database-dev'
          # port: 5984
  tls:
    secretName: {{ .Values.tls.tlsSecret | squote }}
